### ISSUE TITLE
Only last attribute of wasDerivedFrom is showing

### ISSUE THREAD

**Issue by thaylongs** [gems-uff/prov-viewer#6]
Hello, I'm using your tool. When I load an PROV-N file that contains wasDerivedFrom "tag", only the last attribute is showing on graph. For example, consider this PROV-N text:

document
prefix sci <https:/scicumulusc2.wordpress.com>
entity(prov:omafft_38_1,[sci:name = "ORTHOMCL1", sci:fasta_file = "sciPhy/exp/mafft/0/ORTHOMCL1", sci:mafft_file = "sciPhy/exp/mafft/0/ORTHOMCL1.mafft"])
entity(prov:ireadseq_38_1,[sci:name = "ORTHOMCL1", sci:fasta_file = "sciPhy/exp/mafft/0/ORTHOMCL1", sci:mafft_file = "sciPhy/exp/mafft/0/ORTHOMCL1.mafft"])
wasDerivedFrom(prov:ireadseq_38_1, prov:omafft_38_1, prov:a166, -, -,[sci:column = "name", sci:column = "fasta_file", sci:column = "mafft_file"])
endDocument

is showing on graph this: 

![prov-n](https://user-images.githubusercontent.com/5581224/27162179-3e1a2344-5156-11e7-8a8c-4c2873654a32.png)

So, Is it a bug or a developer choice?

I tried compile from master branch(for test with the last version), but the application is throwing a NullPointerException 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at br.uff.ic.utility.graph.GraphObject.getAttributeValues(GraphObject.java:144)
	at br.uff.ic.utility.graph.Edge.getEdgeFrequency(Edge.java:462)
	at br.uff.ic.utility.graph.Edge.getEdgeTooltip(Edge.java:282)
	at br.uff.ic.provviewer.GUI.GuiTooltip$2.transform(GuiTooltip.java:61)
	at br.uff.ic.provviewer.GUI.GuiTooltip$2.transform(GuiTooltip.java:58)
	at edu.uci.ics.jung.visualization.VisualizationViewer.getToolTipText(VisualizationViewer.java:204)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Kohwalter** [comment]
Thaylon,

The edge's optional attribute from your example is: [sci:column = "name",
sci:column = "fasta_file", sci:column = "mafft_file"]
This means we have 3 potentional attributes:

   1. sci:column = "name"
   2. sci:column = "fasta_file"
   3. sci:column = "mafft_file"


All attributes are composed of a NAME and a VALUE
For this example, the name of each attribute is:

   1. sci:column
   2. sci:column
   3. sci:column


Note that all three have the same name. Thus the tool think it is the same
attribute because it uses a HashMap to store attributes, where the
attribute NAME is the key.
You can solve this in two ways:

   1. Change the name of each attribute. For example: sci:column_1,
   sci:column_2, sci:column_3
   2. Or make just one attribute with 3 values separated by anything but a
   comma (since comma is the optional attribute separator): sci:column: "name"
   / "fasta_file" / "mafft_file"


Observation: You got that error from the master branch because I didn't
modify the PROVN reader to be compatible with the new features in the tool
that are related to merging graphs. I already added a fix for it.

Troy Kohwalter

>

**Comment by thaylongs** [comment]
Now I Get It, thank you for the answer.
